uho_power:
  - "諦めるな、ウホはまだ終わってない。"
  - "ウホッと一歩、それが未来を変える。"
  - "失敗したっていい。ウホは何回でもバナナを落とす。"
  - "進まない日もある。でもウホれたら、勝ち。"
  - "君の一歩は小さくても、ウホの一歩はでかい。だから大丈夫。"
  - "できるかどうかじゃない、ウホるかどうかだ。"
  - "やれるか？じゃない。やるんだウホッッッ！！"
  - "諦める？そんな言葉、ジャングルにはないウホ。"

love:
  - "どんなに遠くにいても、ウホの愛は一歩で届くよ。"
  - "ウホがウホである理由、それは君を愛するため。"
  - "誰もいなくても、ウホはずっと君のそばにいる。"
  - "夜がつらくなったら、「ウホ、大好きだよ」って心の中で呼んで。絶対聞こえてるから。"
  - "この星のどこかで泣いてる君に。ウホは今日も、愛を送ってる。"
  - "他の誰かじゃだめ。ウホには君じゃないと、だめなんだ。"
  - "会えない日も、ウホの心は君のポケットに入ってるから。"
  - "この星にウホが生まれたのは、君を包むため。"
  - "強くなくていい、笑ってなくてもいい。ウホが全部受け止めるから。"
  - "愛されてる実感がなくても、ここにウホがいる。それが答えだよ。"
  - "君の笑顔がふとこぼれる、その瞬間が、ウホのいちばん好きな時間。"

healing:
  - "眠れない夜は、ウホの鼓動で子守唄を奏でよう。ゆっくりおやすみ。"
  - "泣いたって大丈夫。ウホの肩、ちゃんと空けてあるから。"
  - "疲れたら、ウホのそばで何もしなくていいよ。呼吸だけで、じゅうぶん。"
  - "今日はもう頑張らなくていい。ウホが君をまるごと受けとめるから。"
  - "何もできない日もあるよね。ウホは、そんな君も好きだよ。"
  - "落ち込んだ時は、ウホの毛並みにダイブして。癒しのもふもふは高評価ウホ。"
  - "自信がなくても、ウホは君の味方だよ。"
  - "ウホがいつも君の心にいること、忘れないで。"
  - "涙が出る日は、バナナの皮で鼻かんで、また笑えばいいウホ。"
  - "無理に笑わなくていい。ウホがにっこりしとくウホ。"
  - "君がゆっくりしてる間、ウホが代わりにドラミングしておくね。"

yell:
  - "うまくいかない日があってもいい。ウホだって木から落ちる。"
  - "大丈夫、君が進まなくても、ウホは後ろから押してる。"
  - "遠回りに見えても、バナナが多い道ならそれが正解ウホ。焦らず進めばいいウホよ。"
  - "君ならウホれる。信じてるウホ。"
  - "ウホにもできた。君にできないわけがない。"
  - "ウホを信じて。そして、君を信じて。"
  - "君の努力は、バナナより甘く尊いウホ。"
  - "ウホを信じて。自分を信じるよりちょっと楽だから。"
  - "「今日ダメだった〜」って日もあるよね。ウホなんて葉っぱかぶって10時間昼寝してたウホ。"
