uho_power:
  - "迷ったら、とりあえずウホってみよう。道はその先にある。"
  - "今の君、完全にゴリゴリに最強。あとウホがつけば無敵。"

heart:
  - "どんなに遠くにいても、ウホの愛は一歩で届くよ。"
  - "ウホがウホである理由、それは君を愛するため。"

healing:
  - "眠れない夜は、ウホの鼓動で子守唄を奏でよう。ゆっくりおやすみ。"
  - "泣いたって大丈夫。ウホの肩、ちゃんと空けてあるから。"

yell:
  - "小さな光を信じる力、それが希望ウホ。ウホはホタルに憧れてた時期もあるウホ。"
  - "遠回りに見えても、バナナが多い道ならそれが正解ウホ。焦らず進めばいいウホよ。"
